### ISSUE TITLE
Add Github Sign In

### ISSUE THREAD

**Issue by infiniteoverflow** [glugmvit/Glug-App#17]

**Comment by mornville** [comment]
I can do this 👍

**Comment by infiniteoverflow** [comment]
cool , go ahead :)

**Comment by rish07** [comment]
Is this issue resolved yet? If not, I'd like to take up this issue. @infiniteoverflow

**Comment by infiniteoverflow** [comment]
Sure , go ahead.
There are certain things to keep in mind:

- We are planning to use Firebase Github authentication.
- You can use ur personal account to check the working of the authentication
- Then later we will shift to our official account , which will require juz some minor changes to the key
- And yes , while pushing the changes , make sure you dont push ur api keys and credentials :)


If u have any doubts , feel free to comment here , or u can connect with me on linkedin. i have the profile link in my github bio.

Soo good luck :)

**Comment by rish07** [comment]
Hey @infiniteoverflow, were you able to review the PR?

**Comment by infiniteoverflow** [comment]
sorry buddy , got busy with some personal work.
Just reviewed it...it looks perfect :)

Good Work !! 👍 👍

**Comment by rish07** [comment]
Thank you! @infiniteoverflow
