### ISSUE TITLE
Add a Splash Screen to the App

### ISSUE THREAD

**Issue by infiniteoverflow** [glugmvit/Glug-App#3]
The Splash screen should be the first thing the user should see when he/she opens the app. It should have the Glug MVIT Logo at the center.
Then later we will refactor it to be more user friendly.

**Comment by reocoder** [comment]
i am interested in working on this issue

**Comment by infiniteoverflow** [comment]
Sure , Go ahead. But pranjal is working on the issue of creating the app template first. Once she has done , u can start with this.

**Resource** : https://medium.com/flutter-community/flutter-2019-real-splash-screens-tutorial-16078660c7a1
